server {
    listen 80;
    server_name tikketsolve-systemoneit.uk www.tikketsolve-systemoneit.uk;

    client_max_body_size 50M;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /var/www/ticketSolve/staticfiles/;
    }

    location /media/ {
        alias /var/www/ticketSolve/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/ticketSolve/gunicorn.sock;
    }
}
