server {
    listen 80;
    server_name ticket.yourdomain.com; # Replace with your actual domain/subdomain

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        root /var/www/ticketSolve;
    }

    location /media/ {
        root /var/www/ticketSolve;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
