def language_processor(request):
    lang = request.COOKIES.get('lang', 'th')
    if lang not in ['th', 'en']:
        lang = 'th'
        
    translations = {
        'th': {
            'lang': 'th',
            'dashboard': 'หน้าจอควบคุม',
            'tickets': 'รายการตั๋วปัญหา',
            'reports': 'รายงานประจำเดือน (PDF)',
            'smtp_settings': 'ตั้งค่าระบบ SMTP',
            'logs': 'ประวัติ & Log ระบบ',
            'logout': 'ออกจากระบบ',
            'login': 'เข้าสู่ระบบ',
            'username_or_email': 'ชื่อผู้ใช้งาน หรือ อีเมล (Username or Email)',
            'password': 'รหัสผ่าน (Password)',
            'active_org': 'องค์กร / บริษัท',
            'theme_color': 'ธีมและสี',
            'display_mode': 'โหมดการแสดงผล',
            'dark_mode': 'มืด (Dark)',
            'light_mode': 'สว่าง (Light)',
            'accent_tone': 'โทนสีเน้น (Accent Tone)',
            'open_new_ticket': '➕ เปิด Ticket ใหม่',
            'edit_ticket': '⚙️ แก้ไขข้อมูล Ticket',
            'ticket_details': '📋 รายละเอียดตั๋วปัญหา',
            'title': 'หัวข้อ (Title)',
            'description': 'รายละเอียด (Description)',
            'priority': 'ระดับความสำคัญ (Priority)',
            'status': 'สถานะการดำเนินงาน (Status)',
            'category': 'หมวดหมู่ (Category)',
            'assigned_to': 'ผู้ดูแลรับผิดชอบ (Assigned To)',
            'comments': 'บันทึกความเห็น / การสื่อสาร (Comments)',
            'write_comment': 'เขียนความคิดเห็นเพื่อแจ้งพนักงาน...',
            'post_comment': '💬 โพสต์ความเห็น',
            'back': 'ย้อนกลับ',
            'cancel': 'ยกเลิก',
            'save': '💾 บันทึกข้อมูล',
            'delete': 'ลบ',
            'add_user': '➕ เพิ่มผู้ใช้งานใหม่',
            'edit_user': '⚙️ แก้ไขข้อมูลผู้ใช้',
            'role': 'บทบาทผู้ดูแล',
            'company': 'สังกัดองค์กร',
            'ticket_id': 'หมายเลขตั๋ว',
            'created_by': 'ผู้แจ้ง',
            'created_at': 'วันที่สร้าง',
            'actions': 'จัดการ',
            'no_tickets': 'ไม่พบตั๋วแจ้งปัญหาใดๆ ในระบบ',
            'tech_assigned': 'ช่างเทคนิคที่รับมอบหมาย',
            'reporter': 'ผู้รายงานเคส',
            'manage_users': 'จัดการบัญชีผู้ใช้',
            'manage_companies': 'จัดการองค์กร/บริษัท',
            'system_default_simulation': 'ใช้บัญชี Active เริ่มต้น',
            'edit_ticket_title': 'แก้ไข Ticket',
            'open_new_ticket_title': 'เปิด Ticket ใหม่',
            'back_to_dashboard': 'กลับไปยัง Dashboard',
            'update_ticket_status': 'อัปเดตสถานะและข้อมูล Ticket',
            'create_new_ticket': 'สร้างใบแจ้งปัญหาใหม่',
            'edit_ticket_desc': 'แก้ไขข้อมูลการดำเนินการและลำดับความสำคัญของระบบ',
            'create_ticket_desc': 'กรุณาระบุรายละเอียดข้อผิดพลาดหรือปัญหาของระบบที่ท่านต้องการได้รับบริการความช่วยเหลือ',
            'input_error': 'เกิดข้อผิดพลาดในการป้อนข้อมูล',
            'save_changes': 'บันทึกการแก้ไข',
            'submit_ticket': 'ยืนยันส่งข้อมูล',
            'assignee_desc': 'เฉพาะพนักงาน/แอดมิน ภายในองค์กรเดียวกันที่สามารถรับมอบหมายงานนี้ได้',
            'edit_or_update': 'แก้ไขข้อมูล / อัปเดตสถานะ',
            'ticket_info': 'ข้อมูล Ticket',
            'audit_trail_history': 'ประวัติการเปลี่ยนสถานะและการอัปเดตงาน (Audit Trail History)',
            'no_audit_trail': 'ยังไม่มีประวัติการอัปเดตสถานะสำหรับ Ticket นี้',
            'created_at_label': 'สร้างเมื่อ',
            'updated_at_label': 'แก้ไขล่าสุดเมื่อ',
            'status_label': 'สถานะ',
            'priority_label': 'ระดับความสำคัญ',
            'creator_label': 'ผู้แจ้งเรื่อง',
            'assignee_label': 'ผู้ได้รับมอบหมาย',
            'no_assignee': 'ยังไม่มีผู้รับผิดชอบ',
            'welcome_back': 'ยินดีต้อนรับกลับมา',
            'welcome_desc': 'นี่คือข้อมูลสรุปรายงาน Ticket ทั้งหมดขององค์กรคุณในวันนี้',
            'status_open': 'เปิดใหม่',
            'status_in_progress': 'กำลังดำเนินการ',
            'status_resolved': 'แก้ไขเสร็จสิ้น',
            'status_closed': 'ปิดสมบูรณ์',
            'priority_high': 'สูง (High)',
            'priority_medium': 'ปานกลาง (Medium)',
            'priority_low': 'ต่ำ (Low)',
            'info_sec_tenant': 'ข้อมูลความปลอดภัยและขอบเขตข้อมูล',
            'info_sec_tenant_desc': 'ระบบทำงานอยู่ภายใต้หลักการความปลอดภัยของ Multi-tenant Data Isolation ผู้ใช้งานภายนอกบริษัทจะไม่สามารถมองเห็นข้อมูลหรือตอบโต้กับระบบข้อมูล Ticket ของบริษัทอื่นได้ การดำเนินการแก้ไขหรือกำหนดสถานะจะดำเนินการได้เฉพาะผู้ดูแล (Client Admin) ของบริษัทนั้นๆ',
            'user_count_label': 'จำนวนผู้ใช้ในระบบ',
            'company_count_label': 'จำนวนองค์กรที่เข้าถึง',
            'ticket_list_title': 'รายการ Ticket',
            'clear_filter': '✕ แสดงทั้งหมด (ล้างการกรอง)',
            'showing_count': 'แสดง',
            'of_count': 'จาก',
            'items': 'รายการ',
            'not_assigned': 'ยังไม่ได้มอบหมาย',
            'no_attachment': 'ไม่มีไฟล์แนบ',
            'attachment_label': 'ไฟล์แนบ (Attachment)',
            'download_label': 'ดาวน์โหลดไฟล์แนบ',
            'comments_title': 'ความคิดเห็นและการตอบกลับ',
            'write_comment_placeholder': 'พิมพ์ความคิดเห็นหรือข้อความตอบกลับที่นี่...',
            'submit_comment': 'ส่งความคิดเห็น / ตอบกลับ',
            'no_comments': 'ยังไม่มีการแสดงความคิดเห็นหรือตอบกลับในตั๋วนี้',
            'write_comment': 'เขียนตอบกลับ (Post Reply)',
        },
        'en': {
            'lang': 'en',
            'dashboard': 'Dashboard',
            'tickets': 'Tickets',
            'reports': 'Monthly PDF Report',
            'smtp_settings': 'Outbound SMTP settings',
            'logs': 'Audit Logs',
            'logout': 'Logout',
            'login': 'Login',
            'username_or_email': 'Username or Email',
            'password': 'Password',
            'active_org': 'Active Organization',
            'theme_color': 'Theme & Accent',
            'display_mode': 'Display Mode',
            'dark_mode': 'Dark',
            'light_mode': 'Light',
            'accent_tone': 'Accent Tone',
            'open_new_ticket': '➕ Open New Ticket',
            'edit_ticket': '⚙️ Edit Ticket',
            'ticket_details': '📋 Ticket Details',
            'title': 'Title',
            'description': 'Description',
            'priority': 'Priority',
            'status': 'Status',
            'category': 'Category',
            'assigned_to': 'Assigned To',
            'comments': 'Communication & Comments',
            'write_comment': 'Write your reply or update here...',
            'post_comment': '💬 Post Comment',
            'back': 'Back',
            'cancel': 'Cancel',
            'save': '💾 Save Settings',
            'delete': 'Delete',
            'add_user': '➕ Add New User',
            'edit_user': '⚙️ Edit User',
            'role': 'Role',
            'company': 'Company / Tenant',
            'ticket_id': 'Ticket ID',
            'created_by': 'Created By',
            'created_at': 'Created At',
            'actions': 'Actions',
            'no_tickets': 'No tickets found in the system.',
            'tech_assigned': 'Assigned Technician',
            'reporter': 'Case Reporter',
            'manage_users': 'Manage Users',
            'manage_companies': 'Manage Companies',
            'system_default_simulation': 'Active System Configuration',
            'edit_ticket_title': 'Edit Ticket',
            'open_new_ticket_title': 'Open New Ticket',
            'back_to_dashboard': 'Back to Dashboard',
            'update_ticket_status': 'Update Ticket Status & Info',
            'create_new_ticket': 'Create New Ticket',
            'edit_ticket_desc': 'Edit execution details and system priority',
            'create_ticket_desc': 'Please describe the technical issue or system error you need help with.',
            'input_error': 'Input validation errors occurred',
            'save_changes': 'Save Changes',
            'submit_ticket': 'Submit Ticket',
            'assignee_desc': 'Only employees and administrators within the same organization can be assigned to this ticket.',
            'edit_or_update': 'Edit Info / Update Status',
            'ticket_info': 'Ticket Info',
            'audit_trail_history': 'Status and Update History (Audit Trail)',
            'no_audit_trail': 'No update history found for this ticket.',
            'created_at_label': 'Created at',
            'updated_at_label': 'Last updated',
            'status_label': 'Status',
            'priority_label': 'Priority',
            'creator_label': 'Reporter',
            'assignee_label': 'Assignee',
            'no_assignee': 'Not Assigned',
            'welcome_back': 'Welcome back',
            'welcome_desc': 'Here is a summary of all tickets in your organization today.',
            'status_open': 'Open',
            'status_in_progress': 'In Progress',
            'status_resolved': 'Resolved',
            'status_closed': 'Closed',
            'priority_high': 'High',
            'priority_medium': 'Medium',
            'priority_low': 'Low',
            'info_sec_tenant': 'Security & Scope Info',
            'info_sec_tenant_desc': 'The system operates under Multi-tenant Data Isolation. Users from other companies cannot see or interact with your tickets. Status updates can only be made by designated Client Admins.',
            'user_count_label': 'Users in System',
            'company_count_label': 'Accessed Organizations',
            'ticket_list_title': 'Ticket List',
            'clear_filter': '✕ Show All (Clear Filters)',
            'showing_count': 'Showing',
            'of_count': 'of',
            'items': 'items',
            'not_assigned': 'Not Assigned',
            'no_attachment': 'No attachment',
            'attachment_label': 'Attachment',
            'download_label': 'Download attachment',
            'comments_title': 'Comments & Replies',
            'write_comment_placeholder': 'Type your comment or reply here...',
            'submit_comment': 'Post Comment / Reply',
            'no_comments': 'No comments or replies on this ticket yet.',
            'write_comment': 'Post Reply',
        }
    }
    
    return {
        'current_lang': lang,
        't': translations[lang]
    }
