def language_processor(request):
    translations = {
        'lang': 'en',
        'dashboard': 'Dashboard',
        'tickets': 'Tickets',
        'reports': 'Monthly PDF Report',
        'smtp_settings': 'Outbound SMTP settings',
        'logs': 'Audit Logs',
        'logout': 'Logout',
        'login': 'Login',
        'username_or_email': 'Username or Email',
        'password': 'Password',
        'active_org': 'Active Organization',
        'central_admin': 'System Admin (Central)',
        'theme_color': 'Theme & Accent',
        'display_mode': 'Display Mode',
        'dark_mode': 'Dark',
        'light_mode': 'Light',
        'accent_tone': 'Accent Tone',
        'open_new_ticket': 'Open New Ticket',
        'edit_ticket': '⚙️ Edit Ticket',
        'ticket_details': '📋 Ticket Details',
        'title': 'Title',
        'description': 'Description',
        'priority': 'Priority',
        'status': 'Status',
        'category': 'Category',
        'module_category': 'Module Category',
        'assigned_to': 'Assigned To',
        'comments': 'Communication & Comments',
        'write_comment': 'Write your reply or update here...',
        'post_comment': '💬 Post Comment',
        'back': 'Back',
        'cancel': 'Cancel',
        'save': '💾 Save Settings',
        'delete': 'Delete',
        'add_user': 'Add New User',
        'edit_user': '⚙️ Edit User',
        'role': 'Role',
        'company': 'Company / Tenant',
        'ticket_id': 'Ticket ID',
        'created_by': 'Created By',
        'created_at': 'Created At',
        'actions': 'Actions',
        'no_tickets': 'No tickets found in the system.',
        'tech_assigned': 'Assigned Technician',
        'reporter': 'Case Reporter',
        'manage_users': 'Manage Users',
        'manage_companies': 'Manage Companies',
        'delete_manage_tickets': 'Delete & Manage Tickets',
        'categories_ticket_design': 'Categories & Design',
        'notification_settings': 'Notification Rules',
        'auto_schedule': 'Ticket Auto Schedule',
        'system_default_simulation': 'Active System Configuration',
        'edit_ticket_title': 'Edit Ticket',
        'open_new_ticket_title': 'Open New Ticket',
        'back_to_dashboard': 'Back to Dashboard',
        'update_ticket_status': 'Update Ticket Status & Info',
        'create_new_ticket': 'Create New Ticket',
        'edit_ticket_desc': 'Edit execution details and system priority',
        'create_ticket_desc': 'Please describe the technical issue or system error you need help with.',
        'input_error': 'Input validation errors occurred',
        'save_changes': 'Save Changes',
        'submit_ticket': 'Submit Ticket',
        'assignee_desc': 'Only employees and administrators within the same organization can be assigned to this ticket.',
        'edit_or_update': 'Edit Info / Update Status',
        'ticket_info': 'Ticket Info',
        'audit_trail_history': 'Status & Update History (Audit Trail)',
        'no_audit_trail': 'No update history found for this ticket.',
        'created_at_label': 'Created at',
        'updated_at_label': 'Last updated',
        'status_label': 'Status',
        'priority_label': 'Priority',
        'creator_label': 'Reporter',
        'assignee_label': 'Assignee',
        'no_assignee': 'Not Assigned',
        'welcome_back': 'Welcome back',
        'welcome_desc': 'Here is a summary of all tickets in your organization today.',
        'status_open': 'Open',
        'status_in_progress': 'In Progress',
        'status_resolved': 'Resolved',
        'status_closed': 'Closed',
        'status_deploy_request': 'Deploy Request',
        'status_ready_deploy': 'Ready to Deploy',
        'priority_high': 'High',
        'priority_medium': 'Medium',
        'priority_low': 'Low',
        'info_sec_tenant': 'Security & Scope Info',
        'info_sec_tenant_desc': 'The system operates under Multi-tenant Data Isolation. Users from other companies cannot see or interact with your tickets.',
        'user_count_label': 'Users in System',
        'company_count_label': 'Accessed Organizations',
        'ticket_list_title': 'Ticket List',
        'clear_filter': '✕ Show All (Clear Filters)',
        'showing_count': 'Showing',
        'of_count': 'of',
        'items': 'items',
        'not_assigned': 'Not Assigned',
        'no_attachment': 'No attachment',
        'attachment_label': 'Attachment',
        'download_label': 'Download attachment',
        'comments_title': 'Comments & Replies',
        'write_comment_placeholder': 'Type your comment or reply here...',
        'submit_comment': 'Post Comment / Reply',
        'no_comments': 'No comments or replies on this ticket yet.',
        'total_tickets': 'Total Tickets',
        'system_users': 'System Users',
        'accessed_companies': 'Accessed Companies',
        'smtp_server_list': 'SMTP Server List',
        'add_new_smtp': 'Add New SMTP Server',
        'smtp_server_desc': 'Manage SMTP servers for real outbound email delivery (Gmail, Microsoft 365, Mailgun, or Custom).',
        'host': 'Host / Server',
        'port': 'Port',
        'use_tls': 'Use TLS',
        'use_ssl': 'Use SSL',
        'from_email': 'Sender Email',
        'is_active': 'Status',
        'active': 'Active',
        'inactive': 'Inactive',
        'category_management': 'Categories & Module Management',
        'problem_categories': 'Problem Categories',
        'module_categories': 'Module Categories',
        'add_category': 'Add New Category',
        'category_name': 'Category Name',
        'module_name': 'Module Name',
        'parent_company': 'Parent Company',
        'system_logs': 'System Activity & Audit Logs',
        'audit_log': 'Ticket Audit Log',
        'email_log': 'Email Delivery Log',
        'backup_log': 'Backup Log',
        'user_list_title': 'System Users',
        'user_list_desc': 'List of all employee and admin accounts separated by organization.',
        'add_new_user': 'Add New User',
        'email': 'Email',
        'user_status_active': 'Active',
        'user_status_inactive': 'Inactive',
        'no_users': 'No user accounts found in the system.',
        'company_list_title': 'Manage Companies & Subsidiaries',
        'company_list_desc': 'Manage parent company and subsidiary structures (Multi-tenant Structure).',
        'add_new_company': 'Add New Company',
        'company_name': 'Company Name',
        'code': 'Reference Code',
        'parent_org': 'Parent Organization',
        'subsidiaries': 'Subsidiaries',
        'purge_delete_title': 'Delete & Manage Tickets (SysAdmin Delete)',
        'purge_delete_desc': 'Permanent ticket deletion tool for System Administrators.',
        'purge': 'Permanently Delete (Purge)',
        'resolution_details': 'Resolution Summary Details',
        'resolution_category': 'Resolution Category',
        'resolution_notes': 'Resolution Notes',
        'add_attachment_hint': '+ Add attachments (Select files one by one)',
        'max_file_size_hint': 'Maximum 10 MB per file',
        'app_password_guide_title': 'App Password Setup Guide',
        'google_gmail': 'Google Gmail',
        'microsoft_outlook': 'Microsoft Outlook / Office 365',
        'gmail_steps_title': 'Steps to generate a 16-digit App Password for Gmail (Google):',
        'gmail_step_1': 'Go to your Google Account App Passwords settings page.',
        'gmail_step_2': 'Select "Security" from the left navigation panel.',
        'gmail_step_3': 'Make sure "2-Step Verification" is enabled for your account.',
        'gmail_step_4': 'Click on "2-Step Verification", scroll to the bottom, and select "App passwords".',
        'gmail_step_5': 'Enter an app label (e.g. TicketSolve SMTP) and click "Create".',
        'gmail_step_6': 'Google will generate a random 16-character password.',
        'gmail_step_7': 'Copy this password and paste it into the App Password field in TicketSolve settings.',
        'outlook_steps_title': 'Steps to generate a 16-digit App Password for Outlook / Office 365 / Microsoft 365:',
        'outlook_step_1': 'Go to your Microsoft Account Security settings.',
        'outlook_step_2': 'Sign in and select "Advanced security options".',
        'outlook_step_3': 'Make sure "Two-step verification" is enabled for your account.',
        'outlook_step_4': 'Scroll down to "App passwords" and click "Create a new app password".',
        'outlook_step_5': 'Microsoft will immediately generate a random 16-character password.',
        'outlook_step_6': 'Copy this password and paste it into the App Password field in TicketSolve settings.',
    }
    
    return {
        'current_lang': 'en',
        't': translations
    }
