# Generated by Django 6.0.7 on 2026-07-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_reportviewlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default SMTP', max_length=100)),
                ('provider', models.CharField(choices=[('GMAIL', 'Gmail SMTP'), ('MICROSOFT', 'Microsoft Outlook SMTP'), ('CUSTOM', 'Custom SMTP'), ('SIMULATION', 'Simulation / Console')], default='SIMULATION', max_length=20)),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Administrator'), ('SYSTEM_SUB_ADMIN', 'System Sub-Administrator'), ('CLIENT_ADMIN', 'Client Administrator'), ('CLIENT_USER', 'Client User')], default='CLIENT_USER', max_length=20),
        ),
    ]
