# Generated by Django 6.0.7 on 2026-07-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_smtpconfiguration_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Network / Internet'), ('ACCOUNT', 'Account / Login'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
