# Generated by Django 6.0.7 on 2026-07-14 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='action_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'เปิด Ticket ใหม่'), ('TICKET_UPDATED', 'อัปเดต Ticket'), ('WELCOME_USER', 'ต้อนรับสมาชิกใหม่'), ('COMPANY_REGISTERED', 'ลงทะเบียนบริษัท'), ('MONTHLY_REPORT', 'รายงานประจำเดือน'), ('COMMENT_ADDED', 'แสดงความคิดเห็นใหม่')], max_length=30),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
