# Generated by Django 6.0.7 on 2026-07-17 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_attachment_alter_emaillog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='tickets.company'),
        ),
    ]
