# Generated by Django 6.0.7 on 2026-07-17 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_company_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Network / Internet'), ('ACCOUNT', 'Account / Login'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.CreateModel(
            name='CompanyTicketConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_prefix', models.CharField(blank=True, default='', help_text='เช่น ACME-, SEC-', max_length=10)),
                ('require_resolution_note', models.BooleanField(default=True, help_text='บังคับใส่รายละเอียดวิธีแก้ไขปัญหาเมื่อปิด Ticket')),
                ('custom_help_text', models.TextField(blank=True, default='', help_text='คำแนะนำคำอธิบายประจำฟอร์มแจ้งปัญหาของบริษัท')),
                ('allow_file_attachments', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_config', to='tickets.company')),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution_categories', to='tickets.company')),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to='tickets.resolutioncategory'),
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_code', models.CharField(default='folder', max_length=50)),
                ('color_code', models.CharField(default='#6366f1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='tickets.company')),
            ],
            options={
                'verbose_name_plural': 'Ticket Categories',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketcategory'),
        ),
        migrations.CreateModel(
            name='TicketStatusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('color_badge_class', models.CharField(default='bg-slate-500/10 text-slate-400 border-slate-500/20', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_configs', to='tickets.company')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
