# Generated by Django 6.0.7 on 2026-07-17 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_resolution_notes_alter_ticket_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='custom_fields_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CompanyTicketField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text Input (บรรทัดเดียว)'), ('TEXTAREA', 'Text Area (หลายบรรทัด)'), ('NUMBER', 'Number (ตัวเลข)'), ('SELECT', 'Dropdown Select (ตัวเลือก)'), ('DATE', 'Date Picker (วันที่)'), ('BOOLEAN', 'Checkbox (สวิตช์ ใช่/ไม่ใช่)')], default='TEXT', max_length=20)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='รายการตัวเลือกสำหรับ Dropdown')),
                ('order', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_fields', to='tickets.company')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('company', 'field_key')},
            },
        ),
    ]
