# Generated by Django 6.0.7 on 2026-07-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticketcategory_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DEPLOYMENT_REQUESTED', 'Production Deployment Request'), ('READY_TO_DEPLOY', 'Ready to Deploy'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),

        ),
        migrations.AlterField(
            model_name='ticketauditlog',
            name='new_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DEPLOYMENT_REQUESTED', 'Production Deployment Request'), ('READY_TO_DEPLOY', 'Ready to Deploy'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketauditlog',
            name='old_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DEPLOYMENT_REQUESTED', 'Production Deployment Request'), ('READY_TO_DEPLOY', 'Ready to Deploy'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20, null=True),
        ),
    ]
