# Generated by Django 6.0.7 on 2026-07-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_status_alter_ticketauditlog_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
