# Generated by Django 6.0.7 on 2026-07-17 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_emaillog_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='กฎการตั้งค่าการแจ้งเตือน', max_length=255)),
                ('notify_ticket_created', models.BooleanField(default=True, verbose_name='แจ้งเตือนการเปิด Ticket ใหม่')),
                ('status_notification_mode', models.CharField(choices=[('ALL', 'ทุกสถานะ (All Statuses)'), ('IMPORTANT_ONLY', 'เฉพาะสถานะสำคัญเท่านั้น (Production Deployment Request, Ready to Deploy, Resolved, Closed)'), ('NONE', 'ปิดการแจ้งเตือนการเปลี่ยนสถานะ (None)')], default='ALL', max_length=20, verbose_name='โหมดแจ้งเตือนการเปลี่ยนสถานะ')),
                ('notify_comments', models.BooleanField(default=True, verbose_name='แจ้งเตือนความคิดเห็น / ตอบกลับ')),
                ('apply_to_subsidiaries', models.BooleanField(default=True, verbose_name='บังคับใช้กับบริษัทลูกทั้งหมดด้วย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_configs', to='tickets.company')),
                ('target_users', models.ManyToManyField(blank=True, help_text='หากไม่ระบุผู้ใช้ กฎนี้จะบังคับใช้กับสมาชิกทุกคนในบริษัท', related_name='notification_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
