# Generated by Django 6.0.7 on 2026-07-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_notificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='allowed_statuses',
            field=models.JSONField(blank=True, default=list, verbose_name='รายการสถานะที่เลือกให้แจ้งเตือน'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='status_notification_mode',
            field=models.CharField(choices=[('ALL', 'ทุกสถานะ (All Statuses)'), ('IMPORTANT_ONLY', 'เฉพาะสถานะสำคัญเท่านั้น (Production Deployment Request, Ready to Deploy, Resolved, Closed)'), ('CUSTOM', 'กำหนดเลือกสถานะเฉพาะ (Custom Select Statuses)'), ('NONE', 'ปิดการแจ้งเตือนการเปลี่ยนสถานะ (None)')], default='ALL', max_length=20, verbose_name='โหมดแจ้งเตือนการเปลี่ยนสถานะ'),
        ),
    ]
