# Generated by Django 6.0.7 on 2026-07-19 04:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_notificationconfig_allowed_statuses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อตารางส่ง')),
                ('day_of_month', models.PositiveSmallIntegerField(default=31, help_text='หากเดือนนั้นไม่มีวันที่ระบุ ระบบจะใช้วันสุดท้ายของเดือน', verbose_name='วันที่ส่งของเดือน')),
                ('send_time', models.TimeField(default=datetime.time(17, 0), verbose_name='เวลาส่ง')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('cc_recipients', models.ManyToManyField(blank=True, related_name='monthly_report_schedules_as_cc', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับสำเนา (CC)')),
                ('company', models.ForeignKey(blank=True, help_text='เว้นว่างสำหรับรายงานรวมทุกบริษัท', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_report_schedules', to='tickets.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monthly_report_schedules', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='monthly_report_schedules_as_recipient', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับหลัก')),
                ('smtp_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_report_schedules', to='tickets.smtpconfiguration', verbose_name='บัญชีอีเมลผู้ส่ง')),
            ],
            options={
                'ordering': ['-is_active', 'day_of_month', 'send_time', 'name'],
            },
        ),
    ]
