# Generated by Django 6.0.7 on 2026-07-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_monthlyreportschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreportschedule',
            name='timezone_name',
            field=models.CharField(choices=[('Asia/Bangkok', 'ประเทศไทย (UTC+7)'), ('Asia/Hong_Kong', 'ฮ่องกง (UTC+8)')], default='Asia/Bangkok', max_length=50, verbose_name='เขตเวลา'),
        ),
    ]
