# Generated by Django 6.0.7 on 2026-07-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_monthlyreportschedule_timezone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='delivery_group',
            field=models.UUIDField(blank=True, db_index=True, help_text='รหัสรวมผู้รับ To/CC ของการส่งอีเมลครั้งเดียวกัน', null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='recipient_type',
            field=models.CharField(choices=[('TO', 'ผู้รับหลัก (To)'), ('CC', 'สำเนา (CC)')], default='TO', max_length=2),
        ),
    ]
