# Generated by Django 6.0.7 on 2026-07-19 08:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def initialize_status_changed_at(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    for ticket in Ticket.objects.all().only('id', 'created_at').iterator():
        Ticket.objects.filter(pk=ticket.pk).update(status_changed_at=ticket.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_emaillog_delivery_group_emaillog_recipient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_changed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.RunPython(initialize_status_changed_at, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TicketAutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_age_value', models.PositiveIntegerField(default=24, verbose_name='ระยะเวลา')),
                ('open_age_unit', models.CharField(choices=[('HOURS', 'ชั่วโมง'), ('DAYS', 'วัน')], default='HOURS', max_length=10, verbose_name='หน่วย')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('apply_to_subsidiaries', models.BooleanField(default=True, verbose_name='ใช้กับบริษัทลูก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_automation_config', to='tickets.company', verbose_name='บริษัท')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ticket_automation_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company__name'],
            },
        ),
    ]
