# Generated by Django 6.0.7 on 2026-07-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticket_status_changed_at_ticketautomationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketautomationconfig',
            name='open_age_unit',
            field=models.CharField(choices=[('MINUTES', 'นาที'), ('HOURS', 'ชั่วโมง'), ('DAYS', 'วัน')], default='HOURS', max_length=10, verbose_name='หน่วย'),
        ),
    ]
