# Generated by Django 6.0.7 on 2026-07-22 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_ticketautomationconfig_open_age_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ModuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_code', models.CharField(blank=True, default='cpu', max_length=50)),
                ('color_code', models.CharField(blank=True, default='#10b981', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_categories', to='tickets.company')),
            ],
            options={
                'verbose_name_plural': 'Module Categories',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='module_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.modulecategory'),
        ),
    ]
