# Generated by Django 6.0.7 on 2026-07-23 16:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_backuplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuplog',
            name='backup_type',
            field=models.CharField(choices=[('FULL', 'Full Backup'), ('INCREMENTAL', '2-Hour Incremental')], default='FULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyticketconfig',
            name='custom_help_text',
            field=models.TextField(blank=True, default='', help_text='Help text guidelines displayed at the top of the ticket creation form.'),
        ),
        migrations.AlterField(
            model_name='companyticketconfig',
            name='require_resolution_note',
            field=models.BooleanField(default=True, help_text='Require resolution note when resolving/closing ticket.'),
        ),
        migrations.AlterField(
            model_name='companyticketconfig',
            name='ticket_prefix',
            field=models.CharField(blank=True, default='', help_text='e.g. ACME-, SEC-', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyticketfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text Input (Single Line)'), ('TEXTAREA', 'Text Area (Multi Line)'), ('NUMBER', 'Number'), ('SELECT', 'Dropdown Select'), ('DATE', 'Date Picker'), ('BOOLEAN', 'Checkbox (Yes/No)')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyticketfield',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Dropdown choices options list'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='action_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'New Ticket Created'), ('TICKET_UPDATED', 'Ticket Updated'), ('WELCOME_USER', 'Welcome New User'), ('COMPANY_REGISTERED', 'Company Registered'), ('MONTHLY_REPORT', 'Monthly Report Dispatched'), ('COMMENT_ADDED', 'New Comment Added')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='delivery_group',
            field=models.UUIDField(blank=True, db_index=True, help_text='Recipient mapping ID for single email batch', null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient_type',
            field=models.CharField(choices=[('TO', 'Primary (To)'), ('CC', 'CC')], default='TO', max_length=2),
        ),
        migrations.AlterField(
            model_name='monthlyreportschedule',
            name='cc_recipients',
            field=models.ManyToManyField(blank=True, related_name='monthly_report_schedules_as_cc', to=settings.AUTH_USER_MODEL, verbose_name='CC Recipients'),
        ),
        migrations.AlterField(
            model_name='monthlyreportschedule',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Leave blank to generate a global report across all companies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_report_schedules', to='tickets.company'),
        ),
        migrations.AlterField(
            model_name='monthlyreportschedule',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(default=31, help_text='If the month does not contain this day, the last day of the month will be used', verbose_name='Send Day of Month'),
        ),
        migrations.AlterField(
            model_name='monthlyreportschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='monthlyreportschedule',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Schedule Name'),
        ),
        migrations.AlterField(
            model_name='monthlyreportschedule',
            name='recipients',
            field=models.ManyToManyField(related_name='monthly_report_schedules_as_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Primary Recipients'),
        ),
        migrations.AlterField(
            model_name='monthlyreportschedule',
            name='send_time',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Send Time'),
        ),
        migrations.AlterField(
            model_name='monthlyreportschedule',
            name='smtp_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_report_schedules', to='tickets.smtpconfiguration', verbose_name='Sender SMTP Account'),
        ),
        migrations.AlterField(
            model_name='monthlyreportschedule',
            name='timezone_name',
            field=models.CharField(choices=[('Asia/Bangkok', 'Bangkok (UTC+7)'), ('Asia/Hong_Kong', 'Hong Kong (UTC+8)')], default='Asia/Bangkok', max_length=50, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='allowed_statuses',
            field=models.JSONField(blank=True, default=list, verbose_name='Notify on Selected Statuses'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='apply_to_subsidiaries',
            field=models.BooleanField(default=True, verbose_name='Apply to All Subsidiaries'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='name',
            field=models.CharField(default='Notification Configuration Rule', max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='notify_comments',
            field=models.BooleanField(default=True, verbose_name='Notify on Comments & Replies'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='notify_ticket_created',
            field=models.BooleanField(default=True, verbose_name='Notify on New Ticket Created'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='status_notification_mode',
            field=models.CharField(choices=[('ALL', 'All Statuses'), ('IMPORTANT_ONLY', 'Important Statuses Only (Production Deployment Request, Ready to Deploy, Resolved, Closed)'), ('CUSTOM', 'Custom Select Statuses'), ('NONE', 'Disabled (None)')], default='ALL', max_length=20, verbose_name='Status Change Notification Mode'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='If no user is specified, this rule applies to all members of the company.', related_name='notification_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketautomationconfig',
            name='apply_to_subsidiaries',
            field=models.BooleanField(default=True, verbose_name='Apply to Subsidiaries'),
        ),
        migrations.AlterField(
            model_name='ticketautomationconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_automation_config', to='tickets.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='ticketautomationconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ticketautomationconfig',
            name='open_age_unit',
            field=models.CharField(choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days')], default='HOURS', max_length=10, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='ticketautomationconfig',
            name='open_age_value',
            field=models.PositiveIntegerField(default=24, verbose_name='Duration'),
        ),
    ]
