# Generated by Django 6.0.7 on 2026-08-01 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_backuplog_backup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='backup_type',
            field=models.CharField(choices=[('FULL', 'Full Backup'), ('INCREMENTAL', 'Incremental Backup'), ('SYSTEM', 'System Data (No Tickets)')], default='FULL', max_length=20),
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.BooleanField(default=True, editable=False, unique=True)),
                ('incremental_is_active', models.BooleanField(default=True)),
                ('incremental_interval_minutes', models.PositiveIntegerField(choices=[(60, 'Every 1 hour'), (120, 'Every 2 hours'), (240, 'Every 4 hours'), (360, 'Every 6 hours'), (720, 'Every 12 hours'), (1440, 'Every 1 day')], default=120)),
                ('full_is_active', models.BooleanField(default=True)),
                ('full_interval_minutes', models.PositiveIntegerField(choices=[(1440, 'Every 1 day'), (4320, 'Every 3 days'), (10080, 'Every 7 days'), (20160, 'Every 14 days'), (43200, 'Every 30 days')], default=1440)),
                ('system_is_active', models.BooleanField(default=True)),
                ('system_interval_minutes', models.PositiveIntegerField(choices=[(1440, 'Every 1 day'), (4320, 'Every 3 days'), (10080, 'Every 7 days'), (20160, 'Every 14 days'), (43200, 'Every 30 days')], default=10080)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_backup_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
