# Generated by Django 6.0.7 on 2026-08-01 20:27

import django.db.models.deletion
import django.utils.timezone
import tickets.security
from django.conf import settings
from django.db import migrations, models


def encrypt_existing_smtp_passwords(apps, schema_editor):
    SMTPConfiguration = apps.get_model('tickets', 'SMTPConfiguration')
    for configuration in SMTPConfiguration.objects.exclude(password='').iterator():
        # Assignment plus save routes legacy plaintext through EncryptedCharField.
        configuration.password = configuration.password
        configuration.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_alter_backuplog_backup_type_backupschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('failed_count', models.PositiveSmallIntegerField(default=0)),
                ('window_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='password',
            field=tickets.security.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.RunPython(encrypt_existing_smtp_passwords, migrations.RunPython.noop),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('BLOCKED', 'Blocked')], db_index=True, max_length=10)),
                ('subject_hash', models.CharField(blank=True, default='', max_length=64)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='security_event_time_idx')],
            },
        ),
    ]
