# Generated by Django 5.2.16 on 2026-08-01 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_security_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='simple_password_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='simple_password_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_password_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='simple_password_enabled',
            field=models.BooleanField(default=False, help_text='Allows this user to set a persistent password with a minimum length of 6 characters.'),
        ),
    ]
