# Generated by Django 5.2.16 on 2026-08-02 06:18

import django.db.models.deletion
import django.utils.timezone
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_simple_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtoticketrunlog',
            name='pending_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inboundemailreceipt',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inboundemailreceipt',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundemailreceipt',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_inbound_email_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundemailreceipt',
            name='matched_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='inboundemailreceipt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('IMPORTED', 'Imported'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=20),
        ),
        migrations.CreateModel(
            name='InboundEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tickets.models.inbound_email_attachment_upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.inboundemailreceipt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('message_count', models.PositiveIntegerField(default=1)),
                ('last_subject', models.CharField(blank=True, default='', max_length=255)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('smtp_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_email_contacts', to='tickets.smtpconfiguration')),
            ],
            options={
                'ordering': ['-last_seen_at', 'email'],
                'indexes': [models.Index(fields=['email'], name='inbound_contact_email_idx'), models.Index(fields=['-last_seen_at'], name='inbound_contact_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('smtp_configuration', 'email'), name='unique_inbound_contact_per_smtp')],
            },
        ),
    ]
