# Generated by Django 5.2.16 on 2026-08-08 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_emailtoticketrunlog_pending_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='tickets.ticket'),
        ),
    ]
