# Generated by Django 5.2.16 on 2026-08-14 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_smtpconfiguration_ignore_keyword_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuplog',
            name='format_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Protected rollback archives are excluded from routine retention cleanup.'),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='restore_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='source',
            field=models.CharField(choices=[('GENERATED', 'Generated by TicketSolve'), ('IMPORTED', 'Imported archive')], default='GENERATED', max_length=20),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_backup_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='validation_details',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='validation_status',
            field=models.CharField(choices=[('UNCHECKED', 'Not validated'), ('VALID', 'Validated'), ('INVALID', 'Invalid'), ('LEGACY', 'Legacy archive')], default='UNCHECKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='action_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'New Ticket Created'), ('TICKET_UPDATED', 'Ticket Updated'), ('WELCOME_USER', 'Welcome New User'), ('COMPANY_REGISTERED', 'Company Registered'), ('MONTHLY_REPORT', 'Monthly Report Dispatched'), ('COMMENT_ADDED', 'New Comment Added'), ('MAINTENANCE', 'System Maintenance Notice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('STATUS_CHANGED', 'Ticket status changed'), ('COMMENT_ADDED', 'Comment added'), ('MAINTENANCE', 'System maintenance')], max_length=30),
        ),
        migrations.CreateModel(
            name='BackupUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('temp_filename', models.CharField(max_length=255, unique=True)),
                ('expected_size', models.BigIntegerField()),
                ('received_size', models.BigIntegerField(default=0)),
                ('next_chunk_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('VALIDATING', 'Validating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='UPLOADING', max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=1000)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to='tickets.backuplog')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.BooleanField(default=True, editable=False, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('title', models.CharField(default='Scheduled maintenance', max_length=160)),
                ('message', models.TextField(blank=True, default='TicketSolve is temporarily unavailable while scheduled maintenance is completed.')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('expected_end', models.DateTimeField(blank=True, null=True)),
                ('allow_test_access', models.BooleanField(default=True)),
                ('access_code_hash', models.CharField(blank=True, default='', max_length=255)),
                ('access_version', models.PositiveIntegerField(default=1)),
                ('access_session_minutes', models.PositiveIntegerField(choices=[(30, '30 minutes'), (60, '1 hour'), (120, '2 hours'), (240, '4 hours')], default=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_maintenance_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('VALIDATING', 'Validating'), ('PRE_BACKUP', 'Creating rollback backup'), ('RESTORING', 'Restoring'), ('VERIFYING', 'Verifying'), ('AWAITING_REVIEW', 'Awaiting administrator review'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled back')], default='QUEUED', max_length=30)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('details', models.TextField(blank=True, default='')),
                ('external_log_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restore_jobs', to='tickets.backuplog')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_restore_jobs', to=settings.AUTH_USER_MODEL)),
                ('rollback_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_restore_jobs', to='tickets.backuplog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
